AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  AlexaChatGPTHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: AlexaChatGPTHandlerFunction
      Handler: index.handler  # Points to index.js handler function
      Runtime: nodejs20.x
      CodeUri: .  # Folder containing index.js
      MemorySize: 128
      Timeout: 45
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          CHATGPT_API_KEY: ""
          GOOGLE_MAPS_API_KEY: ""
          SERP_API_KEY: ""
          S3_ACCESS_KEY_ID: ""
          S3_ACCESS_KEY_SECRET: ""
          S3_REGION: ""
          S3_BUCKET_NAME: ""


Outputs:
  AlexaChatGPTHandler:
    Description: "Lambda alexa chatgpt handler name"
    Value: !Ref AlexaChatGPTHandlerFunction

